### ISSUE TITLE
Plugin directory 2.0

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1684]
Collecting various issues regarding plugin directory for better overview:

```[tasklist]
### Tasks
- [ ] https://github.com/getkirby/getkirby.com/issues/1570
- [ ] https://github.com/getkirby/getkirby.com/issues/1234
- [ ] https://github.com/getkirby/getkirby.com/issues/1279
```
